# Generated by Django 5.0.4 on 2024-04-19 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(max_length=50)),
                ('graphics_card', models.CharField(max_length=255)),
                ('cpu', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lucas_app.game')),
            ],
        ),
    ]
